-- v1.5.0 主场存量导入（生产 whl-club）：显式 club_id 版本（由 export_revenue.py 输出改写）
-- 2026-09-18 已在生产执行：stadiums=16 / club_facilities=80，无孤儿行。
-- 重跑会因 stadiums.club_id 主键冲突报错（不会静默重复）；回滚 = DELETE FROM club_facilities; DELETE FROM stadiums;
-- 注意：同目录 stadium-import.sql 是旧版（按 clubs.name 子查询匹配），已被本文件取代，勿再使用——
-- 它按名字匹配，AC米兰/RB莱比锡/巴塞罗那/曼城 4 支平台无俱乐部行的球队会匹配不到，
-- club_id 落 NULL 并触发 rowid 自增，静默写入脏行。
INSERT INTO stadiums (club_id, name, capacity, tier, shell_influence, bonus_points, fans, created_at, updated_at) VALUES
  (110374, '阿特米奥·弗兰基球场', 22000, 1, 0, 0, 1800.0, strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (5, '斯坦福桥球场', 22000, 1, 0, 0, 1800.0, strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (9, '安菲尔德球场', 35000, 1, 0, 0, 1800.0, strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (280, '卡拉伊斯卡基斯球场', 12000, 0, 0, 0, 1800.0, strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (45, '都灵安联球场', 35000, 1, 0, 0, 1836.0, strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (73, '王子公园球场', 35000, 1, 0, 0, 1872.0, strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (33, '绿森林体育场', 12000, 0, 0, 0, 1800.0, strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (21, '慕尼黑安联球场', 35000, 1, 0, 0, 1782.0, strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (11, '老特拉福德球场', 22000, 1, 0, 0, 1764.0, strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (449, '贝尼托·比利亚马林球场', 17000, 0, 0, 0, 1800.0, strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (243, '圣地亚哥·伯纳乌球场', 12000, 0, 0, 0, 1800.0, strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (13, '圣詹姆斯公园球场', 12000, 0, 0, 0, 1800.0, strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (14, '城市球场', 12000, 0, 0, 0, 1800.0, strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (66, '奥林匹克公园球场', 12000, 0, 0, 0, 1800.0, strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (2, '维拉公园球场', 12000, 0, 0, 0, 1800.0, strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (1, '酋长球场', 12000, 0, 0, 0, 1800.0, strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now'));
INSERT INTO club_facilities (club_id, facility_key, level, updated_at) VALUES
  (110374, 'commercial', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (110374, 'broadcast', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (110374, 'pitch', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (110374, 'youth', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (110374, 'medical', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (5, 'commercial', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (5, 'broadcast', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (5, 'pitch', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (5, 'youth', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (5, 'medical', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (9, 'commercial', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (9, 'broadcast', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (9, 'pitch', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (9, 'youth', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (9, 'medical', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (280, 'commercial', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (280, 'broadcast', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (280, 'pitch', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (280, 'youth', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (280, 'medical', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (45, 'commercial', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (45, 'broadcast', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (45, 'pitch', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (45, 'youth', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (45, 'medical', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (73, 'commercial', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (73, 'broadcast', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (73, 'pitch', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (73, 'youth', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (73, 'medical', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (33, 'commercial', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (33, 'broadcast', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (33, 'pitch', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (33, 'youth', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (33, 'medical', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (21, 'commercial', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (21, 'broadcast', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (21, 'pitch', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (21, 'youth', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (21, 'medical', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (11, 'commercial', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (11, 'broadcast', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (11, 'pitch', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (11, 'youth', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (11, 'medical', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (449, 'commercial', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (449, 'broadcast', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (449, 'pitch', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (449, 'youth', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (449, 'medical', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (243, 'commercial', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (243, 'broadcast', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (243, 'pitch', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (243, 'youth', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (243, 'medical', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (13, 'commercial', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (13, 'broadcast', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (13, 'pitch', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (13, 'youth', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (13, 'medical', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (14, 'commercial', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (14, 'broadcast', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (14, 'pitch', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (14, 'youth', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (14, 'medical', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (66, 'commercial', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (66, 'broadcast', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (66, 'pitch', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (66, 'youth', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (66, 'medical', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (2, 'commercial', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (2, 'broadcast', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (2, 'pitch', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (2, 'youth', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (2, 'medical', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (1, 'commercial', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (1, 'broadcast', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (1, 'pitch', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (1, 'youth', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  (1, 'medical', 0, strftime('%Y-%m-%dT%H:%M:%fZ','now'));
