// FC 源列口径（TECH_DESIGN §5.2/§5.4）——对照 FC26db20251217_fixed.xlsx（Base 94 列）
// 与 FC Editor s901 队壳文件（61 列）逐一核对；两源 playerid = ID 同键。
// 存储裁决：查找类只存 ID、名称由前端按 web/assets/ref/*.json 渲染；惯用脚归一化进 players.foot。

export const CHINA_NA_ID = 155; // NationID：China PR（通道 A naID / 通道 B nationality 同表判定）

// PositionID 表（12 个实位 + '-' 占位；FC26db 与 FC Editor Position 文本同集）
export const POSITION_BY_ID: Record<number, string> = {
  0: 'GK',
  3: 'RB',
  5: 'CB',
  7: 'LB',
  10: 'CDM',
  12: 'RM',
  14: 'CM',
  16: 'LM',
  18: 'CAM',
  23: 'RW',
  25: 'ST',
  27: 'LW',
};

export const POSITION_NAMES: readonly string[] = Object.values(POSITION_BY_ID);

// 通道 A（FC26db Base）必需列；值域：CA/PA 1-99、Age 14-50（§5.4 列校验）
export const FC26_REQUIRED_COLUMNS = ['ID', 'Name', 'Age', 'CA', 'PA', 'naID', 'PosID1', 'FootID'] as const;

// 通道 A game_attrs 白名单：ID 键列 + 非查找原值列（含 34 细分属性），71 列。
// 不落库：Name、FootID/Foot（归一化进 foot）、Team/nationality/Position1-4/Role1-5/PlayStyles1-8/PlayStyles+（文本列）。
export const FC26_GAME_ATTR_COLUMNS: readonly string[] = [
  'ID',
  'Age',
  'CA',
  'PA',
  'height',
  'weight',
  'weakfoot',
  'skillmoves',
  'hashighqualityhead',
  'internationalrep',
  'naID',
  'TeamID',
  'PosID1',
  'PosID2',
  'PosID3',
  'PosID4',
  'RoleID1',
  'RoleID2',
  'RoleID3',
  'RoleID4',
  'RoleID5',
  'PSID1',
  'PSID2',
  'PSID3',
  'PSID4',
  'PSID5',
  'PSID6',
  'PSID7',
  'PSID8',
  'PSID9',
  'PSID10',
  'PSID11',
  'PSID12',
  'PSID13',
  'PSID14',
  'PSID15',
  'NumofPS',
  'sprintspeed',
  'acceleration',
  'finishing',
  'positioning',
  'shotpower',
  'longshots',
  'penalties',
  'volleys',
  'vision',
  'crossing',
  'freekickaccuracy',
  'longpassing',
  'shortpassing',
  'curve',
  'agility',
  'balance',
  'reactions',
  'composure',
  'ballcontrol',
  'dribbling',
  'interceptions',
  'headingaccuracy',
  'defensiveawareness',
  'standingtackle',
  'slidingtackle',
  'jumping',
  'stamina',
  'strength',
  'aggression',
  'gkdiving',
  'gkhandling',
  'gkkicking',
  'gkpositioning',
  'gkreflexes',
];

// 通道 B（FC Editor s901）必需列；姓名列 commonname/firstname/lastname 缺一可用
export const FC_EDITOR_REQUIRED_COLUMNS = [
  'playerid',
  'overallrating',
  'potential',
  'Position',
  'preferredfoot',
] as const;

// 通道 B game_attrs：61 列原文归档（role/playstyles 文本无反查表，仅存档展示）
export const FC_EDITOR_GAME_ATTR_COLUMNS: readonly string[] = [
  'playerid',
  'firstname',
  'lastname',
  'commonname',
  'Position',
  'Position2',
  'Position3',
  'Position4',
  'number',
  'teamid',
  'playerjointeamdate',
  'contractvaliduntil',
  'overallrating',
  'potential',
  'birthdate',
  'nationality',
  'preferredfoot',
  'weakfootabilitytypecode',
  'height',
  'weight',
  'finishing',
  'headingaccuracy',
  'longshots',
  'shotpower',
  'volleys',
  'crossing',
  'longpassing',
  'shortpassing',
  'ballcontrol',
  'curve',
  'dribbling',
  'defensiveawareness',
  'slidingtackle',
  'standingtackle',
  'aggression',
  'composure',
  'interceptions',
  'positioning',
  'reactions',
  'vision',
  'acceleration',
  'agility',
  'balance',
  'jumping',
  'sprintspeed',
  'stamina',
  'strength',
  'freekickaccuracy',
  'penalties',
  'gkdiving',
  'gkhandling',
  'gkkicking',
  'gkpositioning',
  'gkreflexes',
  'role1',
  'role2',
  'role3',
  'role4',
  'role5',
  'Playstyles',
  'Playstyles+',
];
